version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./client:/client
    # environment:
    #   - TEMP=temp
    #   - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./client/.env
  api:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server
      - /server/node_modules
    env_file:
      - ./server/.env
  # nginx:
  #   depends_on:
  #     - api
  #     - client
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "3050:80"


# TODO: Npm install does not work on client? needs manual install. Check maybe it is intalled in other location. Ideally, make production build instead.
# also needs: npm install @tensorflow/tfjs
#             npm i @mediapipe/pose
# nginx allso breaks camera thing. But it is probably reasoanble, because of static...




  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: "./server"
  #   # depends_on:
  #   #   - mysql_db
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
  #   # environment:
  #   #   <<: *common-variables
  #   #   MYSQL_HOST_IP: mysql_db
  #   ports:
  #     - "3001:3001"

  # client:
  #   stdin_open: true
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./client
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app
  #   expose:
  #     - '3000'

